DROP DATABASE CODO_A_CODO;
CREATE DATABASE CODO_A_CODO;
USE CODO_A_CODO;
-- 1
CREATE TABLE DEPARTAMENTOS(
DEPT_NUM INT PRIMARY KEY,
NOMBRE_DEPT VARCHAR(30),
PRESUPUESTO INT
);
CREATE TABLE EMPLEADOS(
DNI INT PRIMARY KEY,
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(30),
DEPT_NUM INT,
FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTAMENTOS(DEPT_NUM)
);

INSERT INTO 
DEPARTAMENTOS(DEPT_NUM, NOMBRE_DEPT, PRESUPUESTO)
VALUES 
(14, 'INFORMÁTICA', 80000),
(15,'GESTIÓN',95000),
(16,'COMUNICACIÓN',75000),
(37,'DESARROLLO',65000),
(77,'INVESTIGACIÓN',40000);

INSERT INTO 
EMPLEADOS(DNI,NOMBRE,APELLIDO,DEPT_NUM)
VALUES
(31096678,'JUAN','LOPEZ',14),
(31096675,'MARTIN','ZARABIA',77),
(34269854,'JOSE','VELEZ',77),
(41369852,'PAULA','MADARIAGA',77),
(33698521,'PEDRO','PEREZ',14),
(32698548,'MARIANA','LOPEZ',15),
(42369854,'ABRIL','SANCHEZ',37),
(36125896,'MARTI','JULIA',14),
(36985471,'OMAR','DIAZ',15),
(32145698,'GUADALUPE','PEREZ',77),
(32369854,'BERNARDO','PANTERA',37),
(36125965,'LUCIA','PESARO',14),
(31236985,'MARIA','DIAMANTE',14),
(32698547,'CARMEN','BARBIERI',16);

-- 2.1
SELECT APELLIDO
FROM EMPLEADOS;

-- 2.2
SELECT DISTINCT APELLIDO
FROM EMPLEADOS;

-- 2.3
SELECT *
FROM EMPLEADOS
WHERE APELLIDO='LOPEZ';

-- 2.4
SELECT *
FROM EMPLEADOS
WHERE APELLIDO='LOPEZ' OR APELLIDO='PEREZ';

-- 2.5
SELECT *
FROM EMPLEADOS
WHERE DEPT_NUM=14;

-- 2.6
SELECT *
FROM EMPLEADOS
WHERE DEPT_NUM=37 OR DEPT_NUM=77;

-- 2.7
SELECT *
FROM EMPLEADOS
WHERE APELLIDO LIKE 'P%';

-- 2.8
SELECT SUM(PRESUPUESTO)
FROM DEPARTAMENTOS;

-- 2.9
SELECT *
FROM EMPLEADOS;

-- 2.10
SELECT EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, DEPARTAMENTOS.NOMBRE_DEPT, DEPARTAMENTOS.PRESUPUESTO
FROM EMPLEADOS
INNER JOIN DEPARTAMENTOS ON DEPARTAMENTOS.DEPT_NUM=EMPLEADOS.DEPT_NUM; 

-- 2.11
SELECT EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, DEPARTAMENTOS.PRESUPUESTO
FROM EMPLEADOS
INNER JOIN DEPARTAMENTOS ON DEPARTAMENTOS.DEPT_NUM=EMPLEADOS.DEPT_NUM
WHERE DEPARTAMENTOS.PRESUPUESTO>60000; 

-- 2.12
INSERT INTO 
DEPARTAMENTOS(DEPT_NUM, NOMBRE_DEPT, PRESUPUESTO)
VALUES
(11,'CALIDAD',40000);

INSERT INTO
EMPLEADOS(DNI,NOMBRE,APELLIDO,DEPT_NUM)
VALUES
(89267109,'ESTHER','VAZQUEZ', 11);

-- 2.13
UPDATE DEPARTAMENTOS
SET PRESUPUESTO=PRESUPUESTO*0.9
WHERE DEPT_NUM=14;

UPDATE DEPARTAMENTOS
SET PRESUPUESTO=PRESUPUESTO*0.9
WHERE DEPT_NUM=15;

UPDATE DEPARTAMENTOS
SET PRESUPUESTO=PRESUPUESTO*0.9
WHERE DEPT_NUM=16;

UPDATE DEPARTAMENTOS
SET PRESUPUESTO=PRESUPUESTO*0.9
WHERE DEPT_NUM=37;

UPDATE DEPARTAMENTOS
SET PRESUPUESTO=PRESUPUESTO*0.9
WHERE DEPT_NUM=77;

UPDATE DEPARTAMENTOS
SET PRESUPUESTO=PRESUPUESTO*0.9
WHERE DEPT_NUM=11;

-- 2.14
UPDATE EMPLEADOS
SET DEPT_NUM=14
WHERE DEPT_NUM=77;

-- 2.15
DELETE FROM EMPLEADOS
WHERE DEPT_NUM=14;

-- 2.16
DELETE EMPLEADOS
FROM EMPLEADOS
INNER JOIN DEPARTAMENTOS ON DEPARTAMENTOS.DEPT_NUM=EMPLEADOS.DEPT_NUM
WHERE DEPARTAMENTOS.PRESUPUESTO>90000;






